on: [ workflow_dispatch, push, pull_request ]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: Install dependencies
        run: |
          npm install -g markdownlint-cli
      - name: Set up problem matcher
        uses: xt0rted/markdownlint-problem-matcher@v2
      - name: Run markdown linter
        run: |
          markdownlint **/*.md --ignore node_modules --config .github/markdownlint.yml

  spelling:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python programs
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install pyspelling
      - name: Install spellchecker package
        run: |
          sudo apt update
          sudo apt install aspell aspell-pt-br
      - name: Spell check
        run: |
          pyspelling --config .github/pyspelling.yml
